name: Next Build and Deploy CI
run-name: CI - Deploy ${{ inputs.version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Description for Logging
        default: v.0.0.0
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: production
    steps: 
    - name: Logging message Bump
      run: |
        echo "Running with input version: $BUMP_MESSAGE"
      env: 
        BUMP_MESSAGE: ${{ inputs.version }}
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7.27.0
    - name: Setup Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        envkey_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        envkey_DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        envkey_DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
        directory: /home/runner/work/dlp-web/dlp-web
        file_name: .env
        fail_on_empty: false
    - name: Build site with Next
      run: pnpm build
    - name: SSH Deploy & Restart PM2
      uses: easingthemes/ssh-deploy@v4.1.0
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: ${{secrets.PM2_RESTART }}
    - name: Purge Cloudflare cache
      run: |
        curl --fail-with-body -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
        -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        --data '{"purge_everything":true}'
